### ISSUE TITLE
Subdomain not found

### ISSUE THREAD

**Issue by Miramate** [hm-edu/iot-state-monitoring#1]
git install gibt folgende Meldung aus:

git clone https://git.evalgo.org/axxepta/iot/raspberrypi4.git ${HOME}/raspberrypi4

fatal: unable to access 'https://git.evalgo.org/axxepta/iot/raspberrypi4.git/': Could not resolve host: git.evalgo.org

**Comment by mj-stahl** [comment]
Das liegt daran, dass diese Domain nichtmehr aktuell ist. Stattdessen kannst du den Link des aktuellen Github-Repositorys verwenden. Eine detaillierte Anleitung hierzu folgt demnächst.
